INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CUDA_BEAMFORMER Cuda_Beamformer)

FIND_PATH(
    CUDA_BEAMFORMER_INCLUDE_DIRS
    NAMES Cuda_Beamformer/api.h
    HINTS $ENV{CUDA_BEAMFORMER_DIR}/include
        ${PC_CUDA_BEAMFORMER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CUDA_BEAMFORMER_LIBRARIES
    NAMES gnuradio-Cuda_Beamformer
    HINTS $ENV{CUDA_BEAMFORMER_DIR}/lib
        ${PC_CUDA_BEAMFORMER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CUDA_BEAMFORMER DEFAULT_MSG CUDA_BEAMFORMER_LIBRARIES CUDA_BEAMFORMER_INCLUDE_DIRS)
MARK_AS_ADVANCED(CUDA_BEAMFORMER_LIBRARIES CUDA_BEAMFORMER_INCLUDE_DIRS)

